### ISSUE TITLE
A getStats function?

### ISSUE THREAD

**Issue by rclark** [tmcw/stream-statistics#10]
Curious what you would think of a sort of `getStats` function that would allow you to get the data object without listening for an event? Something like

```javascript
var ss = require('stream-statistics')();
require('fs').createReadStream('/tons/of/numbers').pipe(ss);
function poll() {
  setTimeout(function() {
    var stats = ss.getStats();
    poll();
  }, 100);
}
poll();
```

**Comment by tmcw** [comment]
So, as time has passed, I've come to realize that a stream isn't the right setup for statistical operations. What this library really does is creating a statistical _reducer_, not really a stream, and if I or someone else in the future wants to really implement online statistics 'the right way', node.js streams aren't the right construct. A reduction function or transducer would be the right solution.

For example, if you wanted an online `mean` method, you'd write:

```
var intermediateRecord = { sum: 0, count: 0 };

function meanReducer(function (memo, item) {
  return {
    count: memo.count + 1,
    sum: memo.sum + item
  };
});

function calculateMean(record) {
  return record.sum / record.count;
}

calculateMean([1, 2, 3].reduce(meanReducer));
```
